name: rails-stack-template
description: This is a stack for deploying a Rails Apps + MYSQL DB to Azure
branding:
  icon: 'Azure.svg'
  color: 'blue'
#-------------------------------------------------------------
inputs:
# All values needed to be provided/verified by the user should be defined as inputs.
# Values can be provided using a values file (yaml/json/.env format) or from the UX.
# Default values are defined by stack authors using **default: <Value>**
# All inputs defined here are optional unless they are marked **required: true**
# All inputs will be of String type by default unless specified as **type:boolean**
# All inputs will be considered as non-secrets unless specified as **is_secret:true**
# All inputs will be available for scripts/workflows run as part of stack init
# Any input that is not explicitly configured as Repo/Environment secret will NOT be available in the new stack

 - name: RepoName
   default: myRailsApp
   description: Name of the new repo created from this stack
 - name: Reviewer_Count
   default: 2
   description: Number of required reviewers for PR
   validvalues: 
   - 2
   - 3
   - 4
   - 5
   - 6

#-------------------------------------------------------------

configs:

# Branch protection rules
- branches:
   - name: release_v? #branch name or pattern you want to protect
     parameters:
       enforce-admins: true
       dismiss-stale-reviews: true
       require-code-owner-reviews: true
       required-approving-review-count: ${{ inputs.Reviewer_Count }}
       allow-force-pushes: false
       allow-deletions: false
   
   - name: dev_v? #branch name or pattern you want to protect
     parameters:
       enforce-admins: true
       dismiss-stale-reviews: true
       require-code-owner-reviews: true
       required-approving-review-count: ${{ inputs.Reviewer_Count }}
       allow-force-pushes: false
       allow-deletions: false
