name: test-stack-template
description: This is a stack for testing stacks.
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  - name: input_field
    description: text input field
    required: true
    
  - name: secret_field
    description: secret input field
    is-secret: true
    required: true
    
#-------------------------------------------------------------
configs:
      
 environments: 
    - name: staging
      parameters: 
        protected-branches: false

    - name: production
      parameters: 
        protected-branches: false

