name: test-stack-template
description: This is a test stack
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
 - name: Reviewer_Count
   default: 2
   description: Number of required reviewers for PR
   validvalues: 
   - 2
   - 3
   - 4

configs:

- branches:
   - name: release_v? #branch name or pattern you want to protect
     parameters:
       enforce-admins: true
       dismiss-stale-reviews: true
       require-code-owner-reviews: true
       required-approving-review-count: ${{ inputs.Reviewer_Count }}
       allow-force-pushes: false
       allow-deletions: false
   
   - name: dev_v? #branch name or pattern you want to protect
     parameters:
       enforce-admins: true
       dismiss-stale-reviews: true
       require-code-owner-reviews: true
       required-approving-review-count: ${{ inputs.Reviewer_Count }}
       allow-force-pushes: false
       allow-deletions: false
